name: KrapMaps
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install playwright && playwright install chromium && playwright install-deps chromium
      - run: python fix.py
      - name: Run
        env:
          TIKTOK_USERNAME: ${{ secrets.TIKTOK_USERNAME }}
          TIKTOK_PASSWORD: ${{ secrets.TIKTOK_PASSWORD }}
          INSTAGRAM_TOKEN: ${{ secrets.INSTAGRAM_TOKEN }}
        run: python tiktok_scraper.py
      - run: git config user.name "Bot" && git config user.email "bot@krapmaps.app" && git add krapmaps_stats.json && git diff --staged --quiet || git commit -m "update" && git push
